[package]
name = "day02"
version = "0.1.0"
authors = ["Stephen Herbein <stephen272@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
csv = "1.0.0-beta.5"

[[bin]]
name = "day02"
path = "src/day02.rs"
