[package]
name = "day12"
version = "0.1.0"
authors = ["Stephen Herbein <stephen272@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
enum-primitive-derive = "0.2.1"
num-traits = "^0.1"